// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobposting_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

public interface CloseJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.CloseJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();
}
