// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobposting_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

public interface CloseJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.CloseJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();
}
