// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

public final class EmployerNotificationProtos {
  private EmployerNotificationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_NotifyEmployerInvitationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_NotifyEmployerInvitationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_NotifyApplicantCountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_NotifyApplicantCountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7protos/service/employer_notification_s" +
      "ervice.grpc.proto\022\016protos.service\032,proto" +
      "s/domain/invitation_response.grpc.proto\032" +
      "(protos/domain/applicant_count.grpc.prot" +
      "o\".\n NotifyEmployerInvitationResponse\022\n\n" +
      "\002id\030\001 \001(\t\"*\n\034NotifyApplicantCountRespons" +
      "e\022\n\n\002id\030\001 \001(\t2\353\001\n\033EmployerNotificationSe" +
      "rvice\022g\n\020NotifyInvitation\022!.protos.domai" +
      "n.InvitationResponse\0320.protos.service.No" +
      "tifyEmployerInvitationResponse\022c\n\024Notify" +
      "ApplicantCount\022\035.protos.domain.Applicant" +
      "Count\032,.protos.service.NotifyApplicantCo" +
      "untResponseBv\n$com.wanpng.notification.g" +
      "rpc.serviceB\032EmployerNotificationProtosP" +
      "\001Z0github.com/wanpng/notification-grpc/g" +
      "rpc/serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wanpng.notification.grpc.domain.InvitationResponseProtos.getDescriptor(),
          com.wanpng.notification.grpc.domain.ApplicationCountProtos.getDescriptor(),
        });
    internal_static_protos_service_NotifyEmployerInvitationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_service_NotifyEmployerInvitationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_NotifyEmployerInvitationResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_protos_service_NotifyApplicantCountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_service_NotifyApplicantCountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_NotifyApplicantCountResponse_descriptor,
        new java.lang.String[] { "Id", });
    com.wanpng.notification.grpc.domain.InvitationResponseProtos.getDescriptor();
    com.wanpng.notification.grpc.domain.ApplicationCountProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
