// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

public final class JobseekerNotificationProtos {
  private JobseekerNotificationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_NotifyJobseekerInvitationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_NotifyJobseekerInvitationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_NotifyApplicationStatusChangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_NotifyApplicationStatusChangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_NotifyApplicationStatusChangeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_NotifyApplicationStatusChangeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8protos/service/jobseeker_notification_" +
      "service.grpc.proto\022\016protos.service\032+prot" +
      "os/domain/invitation_request.grpc.proto\032" +
      "2protos/domain/application_status_change" +
      ".grpc.proto\"/\n!NotifyJobseekerInvitation" +
      "Response\022\n\n\002id\030\001 \001(\t\"p\n$NotifyApplicatio" +
      "nStatusChangeRequest\022H\n\030applicationStatu" +
      "sChanges\030\001 \003(\0132&.protos.domain.Applicati" +
      "onStatusChange\"3\n%NotifyApplicationStatu" +
      "sChangeResponse\022\n\n\002id\030\001 \001(\t2\226\002\n\034Jobseeke" +
      "rNotificationService\022g\n\020NotifyInvitation" +
      "\022 .protos.domain.InvitationRequest\0321.pro" +
      "tos.service.NotifyJobseekerInvitationRes" +
      "ponse\022\214\001\n\035NotifyApplicationStatusChange\022" +
      "4.protos.service.NotifyApplicationStatus" +
      "ChangeRequest\0325.protos.service.NotifyApp" +
      "licationStatusChangeResponseBw\n$com.wanp" +
      "ng.notification.grpc.serviceB\033JobseekerN" +
      "otificationProtosP\001Z0github.com/wanpng/n" +
      "otification-grpc/grpc/serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wanpng.notification.grpc.domain.InvitationRequestProtos.getDescriptor(),
          com.wanpng.notification.grpc.domain.ApplicationStatusChangeProtos.getDescriptor(),
        });
    internal_static_protos_service_NotifyJobseekerInvitationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_service_NotifyJobseekerInvitationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_NotifyJobseekerInvitationResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_protos_service_NotifyApplicationStatusChangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_service_NotifyApplicationStatusChangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_NotifyApplicationStatusChangeRequest_descriptor,
        new java.lang.String[] { "ApplicationStatusChanges", });
    internal_static_protos_service_NotifyApplicationStatusChangeResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_service_NotifyApplicationStatusChangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_NotifyApplicationStatusChangeResponse_descriptor,
        new java.lang.String[] { "Id", });
    com.wanpng.notification.grpc.domain.InvitationRequestProtos.getDescriptor();
    com.wanpng.notification.grpc.domain.ApplicationStatusChangeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
