// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

public interface NotifyDailyJobAlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.NotifyDailyJobAlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  java.util.List<com.wanpng.notification.grpc.domain.DailyJobAlertNotification> 
      getDailyJobAlertNotificationsList();
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  com.wanpng.notification.grpc.domain.DailyJobAlertNotification getDailyJobAlertNotifications(int index);
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  int getDailyJobAlertNotificationsCount();
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  java.util.List<? extends com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder> 
      getDailyJobAlertNotificationsOrBuilderList();
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder getDailyJobAlertNotificationsOrBuilder(
      int index);
}
