// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

public interface NotifyInterviewScheduleDeletedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.NotifyInterviewScheduleDeletedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 statusId = 1;</code>
   * @return The statusId.
   */
  int getStatusId();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
