// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

/**
 * Protobuf type {@code protos.service.NotifyDailyJobAlertRequest}
 */
public final class NotifyDailyJobAlertRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.NotifyDailyJobAlertRequest)
    NotifyDailyJobAlertRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NotifyDailyJobAlertRequest.newBuilder() to construct.
  private NotifyDailyJobAlertRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NotifyDailyJobAlertRequest() {
    dailyJobAlertNotifications_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NotifyDailyJobAlertRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NotifyDailyJobAlertRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              dailyJobAlertNotifications_ = new java.util.ArrayList<com.wanpng.notification.grpc.domain.DailyJobAlertNotification>();
              mutable_bitField0_ |= 0x00000001;
            }
            dailyJobAlertNotifications_.add(
                input.readMessage(com.wanpng.notification.grpc.domain.DailyJobAlertNotification.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        dailyJobAlertNotifications_ = java.util.Collections.unmodifiableList(dailyJobAlertNotifications_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyDailyJobAlertRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyDailyJobAlertRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest.class, com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest.Builder.class);
  }

  public static final int DAILY_JOB_ALERT_NOTIFICATIONS_FIELD_NUMBER = 1;
  private java.util.List<com.wanpng.notification.grpc.domain.DailyJobAlertNotification> dailyJobAlertNotifications_;
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.wanpng.notification.grpc.domain.DailyJobAlertNotification> getDailyJobAlertNotificationsList() {
    return dailyJobAlertNotifications_;
  }
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder> 
      getDailyJobAlertNotificationsOrBuilderList() {
    return dailyJobAlertNotifications_;
  }
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  @java.lang.Override
  public int getDailyJobAlertNotificationsCount() {
    return dailyJobAlertNotifications_.size();
  }
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.notification.grpc.domain.DailyJobAlertNotification getDailyJobAlertNotifications(int index) {
    return dailyJobAlertNotifications_.get(index);
  }
  /**
   * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder getDailyJobAlertNotificationsOrBuilder(
      int index) {
    return dailyJobAlertNotifications_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dailyJobAlertNotifications_.size(); i++) {
      output.writeMessage(1, dailyJobAlertNotifications_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dailyJobAlertNotifications_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dailyJobAlertNotifications_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest)) {
      return super.equals(obj);
    }
    com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest other = (com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest) obj;

    if (!getDailyJobAlertNotificationsList()
        .equals(other.getDailyJobAlertNotificationsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDailyJobAlertNotificationsCount() > 0) {
      hash = (37 * hash) + DAILY_JOB_ALERT_NOTIFICATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getDailyJobAlertNotificationsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.NotifyDailyJobAlertRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.NotifyDailyJobAlertRequest)
      com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyDailyJobAlertRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyDailyJobAlertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest.class, com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest.Builder.class);
    }

    // Construct using com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDailyJobAlertNotificationsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dailyJobAlertNotificationsBuilder_ == null) {
        dailyJobAlertNotifications_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dailyJobAlertNotificationsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyDailyJobAlertRequest_descriptor;
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest getDefaultInstanceForType() {
      return com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest build() {
      com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest buildPartial() {
      com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest result = new com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest(this);
      int from_bitField0_ = bitField0_;
      if (dailyJobAlertNotificationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          dailyJobAlertNotifications_ = java.util.Collections.unmodifiableList(dailyJobAlertNotifications_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dailyJobAlertNotifications_ = dailyJobAlertNotifications_;
      } else {
        result.dailyJobAlertNotifications_ = dailyJobAlertNotificationsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest) {
        return mergeFrom((com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest other) {
      if (other == com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest.getDefaultInstance()) return this;
      if (dailyJobAlertNotificationsBuilder_ == null) {
        if (!other.dailyJobAlertNotifications_.isEmpty()) {
          if (dailyJobAlertNotifications_.isEmpty()) {
            dailyJobAlertNotifications_ = other.dailyJobAlertNotifications_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDailyJobAlertNotificationsIsMutable();
            dailyJobAlertNotifications_.addAll(other.dailyJobAlertNotifications_);
          }
          onChanged();
        }
      } else {
        if (!other.dailyJobAlertNotifications_.isEmpty()) {
          if (dailyJobAlertNotificationsBuilder_.isEmpty()) {
            dailyJobAlertNotificationsBuilder_.dispose();
            dailyJobAlertNotificationsBuilder_ = null;
            dailyJobAlertNotifications_ = other.dailyJobAlertNotifications_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dailyJobAlertNotificationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDailyJobAlertNotificationsFieldBuilder() : null;
          } else {
            dailyJobAlertNotificationsBuilder_.addAllMessages(other.dailyJobAlertNotifications_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wanpng.notification.grpc.domain.DailyJobAlertNotification> dailyJobAlertNotifications_ =
      java.util.Collections.emptyList();
    private void ensureDailyJobAlertNotificationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        dailyJobAlertNotifications_ = new java.util.ArrayList<com.wanpng.notification.grpc.domain.DailyJobAlertNotification>(dailyJobAlertNotifications_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.notification.grpc.domain.DailyJobAlertNotification, com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder, com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder> dailyJobAlertNotificationsBuilder_;

    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public java.util.List<com.wanpng.notification.grpc.domain.DailyJobAlertNotification> getDailyJobAlertNotificationsList() {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dailyJobAlertNotifications_);
      } else {
        return dailyJobAlertNotificationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public int getDailyJobAlertNotificationsCount() {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        return dailyJobAlertNotifications_.size();
      } else {
        return dailyJobAlertNotificationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.DailyJobAlertNotification getDailyJobAlertNotifications(int index) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        return dailyJobAlertNotifications_.get(index);
      } else {
        return dailyJobAlertNotificationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder setDailyJobAlertNotifications(
        int index, com.wanpng.notification.grpc.domain.DailyJobAlertNotification value) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDailyJobAlertNotificationsIsMutable();
        dailyJobAlertNotifications_.set(index, value);
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder setDailyJobAlertNotifications(
        int index, com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder builderForValue) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        ensureDailyJobAlertNotificationsIsMutable();
        dailyJobAlertNotifications_.set(index, builderForValue.build());
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder addDailyJobAlertNotifications(com.wanpng.notification.grpc.domain.DailyJobAlertNotification value) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDailyJobAlertNotificationsIsMutable();
        dailyJobAlertNotifications_.add(value);
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder addDailyJobAlertNotifications(
        int index, com.wanpng.notification.grpc.domain.DailyJobAlertNotification value) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDailyJobAlertNotificationsIsMutable();
        dailyJobAlertNotifications_.add(index, value);
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder addDailyJobAlertNotifications(
        com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder builderForValue) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        ensureDailyJobAlertNotificationsIsMutable();
        dailyJobAlertNotifications_.add(builderForValue.build());
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder addDailyJobAlertNotifications(
        int index, com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder builderForValue) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        ensureDailyJobAlertNotificationsIsMutable();
        dailyJobAlertNotifications_.add(index, builderForValue.build());
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder addAllDailyJobAlertNotifications(
        java.lang.Iterable<? extends com.wanpng.notification.grpc.domain.DailyJobAlertNotification> values) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        ensureDailyJobAlertNotificationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dailyJobAlertNotifications_);
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder clearDailyJobAlertNotifications() {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        dailyJobAlertNotifications_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public Builder removeDailyJobAlertNotifications(int index) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        ensureDailyJobAlertNotificationsIsMutable();
        dailyJobAlertNotifications_.remove(index);
        onChanged();
      } else {
        dailyJobAlertNotificationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder getDailyJobAlertNotificationsBuilder(
        int index) {
      return getDailyJobAlertNotificationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder getDailyJobAlertNotificationsOrBuilder(
        int index) {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        return dailyJobAlertNotifications_.get(index);  } else {
        return dailyJobAlertNotificationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public java.util.List<? extends com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder> 
         getDailyJobAlertNotificationsOrBuilderList() {
      if (dailyJobAlertNotificationsBuilder_ != null) {
        return dailyJobAlertNotificationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dailyJobAlertNotifications_);
      }
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder addDailyJobAlertNotificationsBuilder() {
      return getDailyJobAlertNotificationsFieldBuilder().addBuilder(
          com.wanpng.notification.grpc.domain.DailyJobAlertNotification.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder addDailyJobAlertNotificationsBuilder(
        int index) {
      return getDailyJobAlertNotificationsFieldBuilder().addBuilder(
          index, com.wanpng.notification.grpc.domain.DailyJobAlertNotification.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.DailyJobAlertNotification daily_job_alert_notifications = 1;</code>
     */
    public java.util.List<com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder> 
         getDailyJobAlertNotificationsBuilderList() {
      return getDailyJobAlertNotificationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.notification.grpc.domain.DailyJobAlertNotification, com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder, com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder> 
        getDailyJobAlertNotificationsFieldBuilder() {
      if (dailyJobAlertNotificationsBuilder_ == null) {
        dailyJobAlertNotificationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wanpng.notification.grpc.domain.DailyJobAlertNotification, com.wanpng.notification.grpc.domain.DailyJobAlertNotification.Builder, com.wanpng.notification.grpc.domain.DailyJobAlertNotificationOrBuilder>(
                dailyJobAlertNotifications_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        dailyJobAlertNotifications_ = null;
      }
      return dailyJobAlertNotificationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.NotifyDailyJobAlertRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.service.NotifyDailyJobAlertRequest)
  private static final com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest();
  }

  public static com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NotifyDailyJobAlertRequest>
      PARSER = new com.google.protobuf.AbstractParser<NotifyDailyJobAlertRequest>() {
    @java.lang.Override
    public NotifyDailyJobAlertRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NotifyDailyJobAlertRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NotifyDailyJobAlertRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NotifyDailyJobAlertRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.notification.grpc.service.NotifyDailyJobAlertRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

