// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

/**
 * Protobuf type {@code protos.service.NotifyInterviewScheduleDeletedRequest}
 */
public final class NotifyInterviewScheduleDeletedRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.NotifyInterviewScheduleDeletedRequest)
    NotifyInterviewScheduleDeletedRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NotifyInterviewScheduleDeletedRequest.newBuilder() to construct.
  private NotifyInterviewScheduleDeletedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NotifyInterviewScheduleDeletedRequest() {
    jobseekerInterviewSchedules_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NotifyInterviewScheduleDeletedRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NotifyInterviewScheduleDeletedRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jobseekerInterviewSchedules_ = new java.util.ArrayList<com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobseekerInterviewSchedules_.add(
                input.readMessage(com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jobseekerInterviewSchedules_ = java.util.Collections.unmodifiableList(jobseekerInterviewSchedules_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyInterviewScheduleDeletedRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyInterviewScheduleDeletedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest.class, com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest.Builder.class);
  }

  public static final int JOBSEEKERINTERVIEWSCHEDULES_FIELD_NUMBER = 1;
  private java.util.List<com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule> jobseekerInterviewSchedules_;
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule> getJobseekerInterviewSchedulesList() {
    return jobseekerInterviewSchedules_;
  }
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder> 
      getJobseekerInterviewSchedulesOrBuilderList() {
    return jobseekerInterviewSchedules_;
  }
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  @java.lang.Override
  public int getJobseekerInterviewSchedulesCount() {
    return jobseekerInterviewSchedules_.size();
  }
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule getJobseekerInterviewSchedules(int index) {
    return jobseekerInterviewSchedules_.get(index);
  }
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder getJobseekerInterviewSchedulesOrBuilder(
      int index) {
    return jobseekerInterviewSchedules_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobseekerInterviewSchedules_.size(); i++) {
      output.writeMessage(1, jobseekerInterviewSchedules_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobseekerInterviewSchedules_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobseekerInterviewSchedules_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest)) {
      return super.equals(obj);
    }
    com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest other = (com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest) obj;

    if (!getJobseekerInterviewSchedulesList()
        .equals(other.getJobseekerInterviewSchedulesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobseekerInterviewSchedulesCount() > 0) {
      hash = (37 * hash) + JOBSEEKERINTERVIEWSCHEDULES_FIELD_NUMBER;
      hash = (53 * hash) + getJobseekerInterviewSchedulesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.NotifyInterviewScheduleDeletedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.NotifyInterviewScheduleDeletedRequest)
      com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyInterviewScheduleDeletedRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyInterviewScheduleDeletedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest.class, com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest.Builder.class);
    }

    // Construct using com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobseekerInterviewSchedulesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        jobseekerInterviewSchedules_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobseekerInterviewSchedulesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyInterviewScheduleDeletedRequest_descriptor;
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest getDefaultInstanceForType() {
      return com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest build() {
      com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest buildPartial() {
      com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest result = new com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest(this);
      int from_bitField0_ = bitField0_;
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobseekerInterviewSchedules_ = java.util.Collections.unmodifiableList(jobseekerInterviewSchedules_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobseekerInterviewSchedules_ = jobseekerInterviewSchedules_;
      } else {
        result.jobseekerInterviewSchedules_ = jobseekerInterviewSchedulesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest) {
        return mergeFrom((com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest other) {
      if (other == com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest.getDefaultInstance()) return this;
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        if (!other.jobseekerInterviewSchedules_.isEmpty()) {
          if (jobseekerInterviewSchedules_.isEmpty()) {
            jobseekerInterviewSchedules_ = other.jobseekerInterviewSchedules_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobseekerInterviewSchedulesIsMutable();
            jobseekerInterviewSchedules_.addAll(other.jobseekerInterviewSchedules_);
          }
          onChanged();
        }
      } else {
        if (!other.jobseekerInterviewSchedules_.isEmpty()) {
          if (jobseekerInterviewSchedulesBuilder_.isEmpty()) {
            jobseekerInterviewSchedulesBuilder_.dispose();
            jobseekerInterviewSchedulesBuilder_ = null;
            jobseekerInterviewSchedules_ = other.jobseekerInterviewSchedules_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobseekerInterviewSchedulesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobseekerInterviewSchedulesFieldBuilder() : null;
          } else {
            jobseekerInterviewSchedulesBuilder_.addAllMessages(other.jobseekerInterviewSchedules_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule> jobseekerInterviewSchedules_ =
      java.util.Collections.emptyList();
    private void ensureJobseekerInterviewSchedulesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobseekerInterviewSchedules_ = new java.util.ArrayList<com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule>(jobseekerInterviewSchedules_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule, com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder, com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder> jobseekerInterviewSchedulesBuilder_;

    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public java.util.List<com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule> getJobseekerInterviewSchedulesList() {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobseekerInterviewSchedules_);
      } else {
        return jobseekerInterviewSchedulesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public int getJobseekerInterviewSchedulesCount() {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        return jobseekerInterviewSchedules_.size();
      } else {
        return jobseekerInterviewSchedulesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule getJobseekerInterviewSchedules(int index) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        return jobseekerInterviewSchedules_.get(index);
      } else {
        return jobseekerInterviewSchedulesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder setJobseekerInterviewSchedules(
        int index, com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule value) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobseekerInterviewSchedulesIsMutable();
        jobseekerInterviewSchedules_.set(index, value);
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder setJobseekerInterviewSchedules(
        int index, com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder builderForValue) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        ensureJobseekerInterviewSchedulesIsMutable();
        jobseekerInterviewSchedules_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder addJobseekerInterviewSchedules(com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule value) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobseekerInterviewSchedulesIsMutable();
        jobseekerInterviewSchedules_.add(value);
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder addJobseekerInterviewSchedules(
        int index, com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule value) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobseekerInterviewSchedulesIsMutable();
        jobseekerInterviewSchedules_.add(index, value);
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder addJobseekerInterviewSchedules(
        com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder builderForValue) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        ensureJobseekerInterviewSchedulesIsMutable();
        jobseekerInterviewSchedules_.add(builderForValue.build());
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder addJobseekerInterviewSchedules(
        int index, com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder builderForValue) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        ensureJobseekerInterviewSchedulesIsMutable();
        jobseekerInterviewSchedules_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder addAllJobseekerInterviewSchedules(
        java.lang.Iterable<? extends com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule> values) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        ensureJobseekerInterviewSchedulesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobseekerInterviewSchedules_);
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder clearJobseekerInterviewSchedules() {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        jobseekerInterviewSchedules_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public Builder removeJobseekerInterviewSchedules(int index) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        ensureJobseekerInterviewSchedulesIsMutable();
        jobseekerInterviewSchedules_.remove(index);
        onChanged();
      } else {
        jobseekerInterviewSchedulesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder getJobseekerInterviewSchedulesBuilder(
        int index) {
      return getJobseekerInterviewSchedulesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder getJobseekerInterviewSchedulesOrBuilder(
        int index) {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        return jobseekerInterviewSchedules_.get(index);  } else {
        return jobseekerInterviewSchedulesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public java.util.List<? extends com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder> 
         getJobseekerInterviewSchedulesOrBuilderList() {
      if (jobseekerInterviewSchedulesBuilder_ != null) {
        return jobseekerInterviewSchedulesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobseekerInterviewSchedules_);
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder addJobseekerInterviewSchedulesBuilder() {
      return getJobseekerInterviewSchedulesFieldBuilder().addBuilder(
          com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder addJobseekerInterviewSchedulesBuilder(
        int index) {
      return getJobseekerInterviewSchedulesFieldBuilder().addBuilder(
          index, com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
     */
    public java.util.List<com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder> 
         getJobseekerInterviewSchedulesBuilderList() {
      return getJobseekerInterviewSchedulesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule, com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder, com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder> 
        getJobseekerInterviewSchedulesFieldBuilder() {
      if (jobseekerInterviewSchedulesBuilder_ == null) {
        jobseekerInterviewSchedulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule, com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule.Builder, com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder>(
                jobseekerInterviewSchedules_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobseekerInterviewSchedules_ = null;
      }
      return jobseekerInterviewSchedulesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.NotifyInterviewScheduleDeletedRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.service.NotifyInterviewScheduleDeletedRequest)
  private static final com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest();
  }

  public static com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NotifyInterviewScheduleDeletedRequest>
      PARSER = new com.google.protobuf.AbstractParser<NotifyInterviewScheduleDeletedRequest>() {
    @java.lang.Override
    public NotifyInterviewScheduleDeletedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NotifyInterviewScheduleDeletedRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NotifyInterviewScheduleDeletedRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NotifyInterviewScheduleDeletedRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.notification.grpc.service.NotifyInterviewScheduleDeletedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

