// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

public interface NotifyEmployerInterviewScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.NotifyEmployerInterviewScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
