// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

public interface NotifyInterviewScheduleDeletedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.NotifyInterviewScheduleDeletedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  java.util.List<com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule> 
      getJobseekerInterviewSchedulesList();
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  com.wanpng.notification.grpc.domain.JobseekerInterviewSchedule getJobseekerInterviewSchedules(int index);
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  int getJobseekerInterviewSchedulesCount();
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  java.util.List<? extends com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder> 
      getJobseekerInterviewSchedulesOrBuilderList();
  /**
   * <code>repeated .protos.domain.JobseekerInterviewSchedule jobseekerInterviewSchedules = 1;</code>
   */
  com.wanpng.notification.grpc.domain.JobseekerInterviewScheduleOrBuilder getJobseekerInterviewSchedulesOrBuilder(
      int index);
}
