// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_notification_service.grpc.proto

package com.wanpng.notification.grpc.service;

/**
 * Protobuf type {@code protos.service.NotifyApplicationStatusChangeRequest}
 */
public final class NotifyApplicationStatusChangeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.NotifyApplicationStatusChangeRequest)
    NotifyApplicationStatusChangeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NotifyApplicationStatusChangeRequest.newBuilder() to construct.
  private NotifyApplicationStatusChangeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NotifyApplicationStatusChangeRequest() {
    applicationStatusChanges_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NotifyApplicationStatusChangeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NotifyApplicationStatusChangeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              applicationStatusChanges_ = new java.util.ArrayList<com.wanpng.notification.grpc.domain.ApplicationStatusChange>();
              mutable_bitField0_ |= 0x00000001;
            }
            applicationStatusChanges_.add(
                input.readMessage(com.wanpng.notification.grpc.domain.ApplicationStatusChange.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        applicationStatusChanges_ = java.util.Collections.unmodifiableList(applicationStatusChanges_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyApplicationStatusChangeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyApplicationStatusChangeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest.class, com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest.Builder.class);
  }

  public static final int APPLICATIONSTATUSCHANGES_FIELD_NUMBER = 1;
  private java.util.List<com.wanpng.notification.grpc.domain.ApplicationStatusChange> applicationStatusChanges_;
  /**
   * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.wanpng.notification.grpc.domain.ApplicationStatusChange> getApplicationStatusChangesList() {
    return applicationStatusChanges_;
  }
  /**
   * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wanpng.notification.grpc.domain.ApplicationStatusChangeOrBuilder> 
      getApplicationStatusChangesOrBuilderList() {
    return applicationStatusChanges_;
  }
  /**
   * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
   */
  @java.lang.Override
  public int getApplicationStatusChangesCount() {
    return applicationStatusChanges_.size();
  }
  /**
   * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.notification.grpc.domain.ApplicationStatusChange getApplicationStatusChanges(int index) {
    return applicationStatusChanges_.get(index);
  }
  /**
   * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.notification.grpc.domain.ApplicationStatusChangeOrBuilder getApplicationStatusChangesOrBuilder(
      int index) {
    return applicationStatusChanges_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < applicationStatusChanges_.size(); i++) {
      output.writeMessage(1, applicationStatusChanges_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < applicationStatusChanges_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, applicationStatusChanges_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest)) {
      return super.equals(obj);
    }
    com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest other = (com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest) obj;

    if (!getApplicationStatusChangesList()
        .equals(other.getApplicationStatusChangesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getApplicationStatusChangesCount() > 0) {
      hash = (37 * hash) + APPLICATIONSTATUSCHANGES_FIELD_NUMBER;
      hash = (53 * hash) + getApplicationStatusChangesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.NotifyApplicationStatusChangeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.NotifyApplicationStatusChangeRequest)
      com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyApplicationStatusChangeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyApplicationStatusChangeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest.class, com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest.Builder.class);
    }

    // Construct using com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getApplicationStatusChangesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (applicationStatusChangesBuilder_ == null) {
        applicationStatusChanges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        applicationStatusChangesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.notification.grpc.service.JobseekerNotificationProtos.internal_static_protos_service_NotifyApplicationStatusChangeRequest_descriptor;
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest getDefaultInstanceForType() {
      return com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest build() {
      com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest buildPartial() {
      com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest result = new com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest(this);
      int from_bitField0_ = bitField0_;
      if (applicationStatusChangesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          applicationStatusChanges_ = java.util.Collections.unmodifiableList(applicationStatusChanges_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.applicationStatusChanges_ = applicationStatusChanges_;
      } else {
        result.applicationStatusChanges_ = applicationStatusChangesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest) {
        return mergeFrom((com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest other) {
      if (other == com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest.getDefaultInstance()) return this;
      if (applicationStatusChangesBuilder_ == null) {
        if (!other.applicationStatusChanges_.isEmpty()) {
          if (applicationStatusChanges_.isEmpty()) {
            applicationStatusChanges_ = other.applicationStatusChanges_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureApplicationStatusChangesIsMutable();
            applicationStatusChanges_.addAll(other.applicationStatusChanges_);
          }
          onChanged();
        }
      } else {
        if (!other.applicationStatusChanges_.isEmpty()) {
          if (applicationStatusChangesBuilder_.isEmpty()) {
            applicationStatusChangesBuilder_.dispose();
            applicationStatusChangesBuilder_ = null;
            applicationStatusChanges_ = other.applicationStatusChanges_;
            bitField0_ = (bitField0_ & ~0x00000001);
            applicationStatusChangesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getApplicationStatusChangesFieldBuilder() : null;
          } else {
            applicationStatusChangesBuilder_.addAllMessages(other.applicationStatusChanges_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wanpng.notification.grpc.domain.ApplicationStatusChange> applicationStatusChanges_ =
      java.util.Collections.emptyList();
    private void ensureApplicationStatusChangesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        applicationStatusChanges_ = new java.util.ArrayList<com.wanpng.notification.grpc.domain.ApplicationStatusChange>(applicationStatusChanges_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.notification.grpc.domain.ApplicationStatusChange, com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder, com.wanpng.notification.grpc.domain.ApplicationStatusChangeOrBuilder> applicationStatusChangesBuilder_;

    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public java.util.List<com.wanpng.notification.grpc.domain.ApplicationStatusChange> getApplicationStatusChangesList() {
      if (applicationStatusChangesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(applicationStatusChanges_);
      } else {
        return applicationStatusChangesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public int getApplicationStatusChangesCount() {
      if (applicationStatusChangesBuilder_ == null) {
        return applicationStatusChanges_.size();
      } else {
        return applicationStatusChangesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.ApplicationStatusChange getApplicationStatusChanges(int index) {
      if (applicationStatusChangesBuilder_ == null) {
        return applicationStatusChanges_.get(index);
      } else {
        return applicationStatusChangesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder setApplicationStatusChanges(
        int index, com.wanpng.notification.grpc.domain.ApplicationStatusChange value) {
      if (applicationStatusChangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApplicationStatusChangesIsMutable();
        applicationStatusChanges_.set(index, value);
        onChanged();
      } else {
        applicationStatusChangesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder setApplicationStatusChanges(
        int index, com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder builderForValue) {
      if (applicationStatusChangesBuilder_ == null) {
        ensureApplicationStatusChangesIsMutable();
        applicationStatusChanges_.set(index, builderForValue.build());
        onChanged();
      } else {
        applicationStatusChangesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder addApplicationStatusChanges(com.wanpng.notification.grpc.domain.ApplicationStatusChange value) {
      if (applicationStatusChangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApplicationStatusChangesIsMutable();
        applicationStatusChanges_.add(value);
        onChanged();
      } else {
        applicationStatusChangesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder addApplicationStatusChanges(
        int index, com.wanpng.notification.grpc.domain.ApplicationStatusChange value) {
      if (applicationStatusChangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApplicationStatusChangesIsMutable();
        applicationStatusChanges_.add(index, value);
        onChanged();
      } else {
        applicationStatusChangesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder addApplicationStatusChanges(
        com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder builderForValue) {
      if (applicationStatusChangesBuilder_ == null) {
        ensureApplicationStatusChangesIsMutable();
        applicationStatusChanges_.add(builderForValue.build());
        onChanged();
      } else {
        applicationStatusChangesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder addApplicationStatusChanges(
        int index, com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder builderForValue) {
      if (applicationStatusChangesBuilder_ == null) {
        ensureApplicationStatusChangesIsMutable();
        applicationStatusChanges_.add(index, builderForValue.build());
        onChanged();
      } else {
        applicationStatusChangesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder addAllApplicationStatusChanges(
        java.lang.Iterable<? extends com.wanpng.notification.grpc.domain.ApplicationStatusChange> values) {
      if (applicationStatusChangesBuilder_ == null) {
        ensureApplicationStatusChangesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, applicationStatusChanges_);
        onChanged();
      } else {
        applicationStatusChangesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder clearApplicationStatusChanges() {
      if (applicationStatusChangesBuilder_ == null) {
        applicationStatusChanges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        applicationStatusChangesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public Builder removeApplicationStatusChanges(int index) {
      if (applicationStatusChangesBuilder_ == null) {
        ensureApplicationStatusChangesIsMutable();
        applicationStatusChanges_.remove(index);
        onChanged();
      } else {
        applicationStatusChangesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder getApplicationStatusChangesBuilder(
        int index) {
      return getApplicationStatusChangesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.ApplicationStatusChangeOrBuilder getApplicationStatusChangesOrBuilder(
        int index) {
      if (applicationStatusChangesBuilder_ == null) {
        return applicationStatusChanges_.get(index);  } else {
        return applicationStatusChangesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public java.util.List<? extends com.wanpng.notification.grpc.domain.ApplicationStatusChangeOrBuilder> 
         getApplicationStatusChangesOrBuilderList() {
      if (applicationStatusChangesBuilder_ != null) {
        return applicationStatusChangesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(applicationStatusChanges_);
      }
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder addApplicationStatusChangesBuilder() {
      return getApplicationStatusChangesFieldBuilder().addBuilder(
          com.wanpng.notification.grpc.domain.ApplicationStatusChange.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder addApplicationStatusChangesBuilder(
        int index) {
      return getApplicationStatusChangesFieldBuilder().addBuilder(
          index, com.wanpng.notification.grpc.domain.ApplicationStatusChange.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.ApplicationStatusChange applicationStatusChanges = 1;</code>
     */
    public java.util.List<com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder> 
         getApplicationStatusChangesBuilderList() {
      return getApplicationStatusChangesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.notification.grpc.domain.ApplicationStatusChange, com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder, com.wanpng.notification.grpc.domain.ApplicationStatusChangeOrBuilder> 
        getApplicationStatusChangesFieldBuilder() {
      if (applicationStatusChangesBuilder_ == null) {
        applicationStatusChangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wanpng.notification.grpc.domain.ApplicationStatusChange, com.wanpng.notification.grpc.domain.ApplicationStatusChange.Builder, com.wanpng.notification.grpc.domain.ApplicationStatusChangeOrBuilder>(
                applicationStatusChanges_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        applicationStatusChanges_ = null;
      }
      return applicationStatusChangesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.NotifyApplicationStatusChangeRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.service.NotifyApplicationStatusChangeRequest)
  private static final com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest();
  }

  public static com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NotifyApplicationStatusChangeRequest>
      PARSER = new com.google.protobuf.AbstractParser<NotifyApplicationStatusChangeRequest>() {
    @java.lang.Override
    public NotifyApplicationStatusChangeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NotifyApplicationStatusChangeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NotifyApplicationStatusChangeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NotifyApplicationStatusChangeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.notification.grpc.service.NotifyApplicationStatusChangeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

