// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employer.grpc.proto

package com.wanpng.notification.grpc.domain;

/**
 * Protobuf type {@code protos.domain.Employer}
 */
public final class Employer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.Employer)
    EmployerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Employer.newBuilder() to construct.
  private Employer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Employer() {
    employerId_ = "";
    companyName_ = "";
    photoUrl_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Employer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Employer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            employerId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            companyName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            photoUrl_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.notification.grpc.domain.EmployerProtos.internal_static_protos_domain_Employer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.notification.grpc.domain.EmployerProtos.internal_static_protos_domain_Employer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.notification.grpc.domain.Employer.class, com.wanpng.notification.grpc.domain.Employer.Builder.class);
  }

  public static final int EMPLOYER_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object employerId_;
  /**
   * <code>string employer_id = 1;</code>
   * @return The employerId.
   */
  @java.lang.Override
  public java.lang.String getEmployerId() {
    java.lang.Object ref = employerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employerId_ = s;
      return s;
    }
  }
  /**
   * <code>string employer_id = 1;</code>
   * @return The bytes for employerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmployerIdBytes() {
    java.lang.Object ref = employerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object companyName_;
  /**
   * <code>string company_name = 2;</code>
   * @return The companyName.
   */
  @java.lang.Override
  public java.lang.String getCompanyName() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyName_ = s;
      return s;
    }
  }
  /**
   * <code>string company_name = 2;</code>
   * @return The bytes for companyName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyNameBytes() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHOTO_URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object photoUrl_;
  /**
   * <code>string photo_url = 3;</code>
   * @return The photoUrl.
   */
  @java.lang.Override
  public java.lang.String getPhotoUrl() {
    java.lang.Object ref = photoUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      photoUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string photo_url = 3;</code>
   * @return The bytes for photoUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhotoUrlBytes() {
    java.lang.Object ref = photoUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      photoUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEmployerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, employerId_);
    }
    if (!getCompanyNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, companyName_);
    }
    if (!getPhotoUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, photoUrl_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEmployerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, employerId_);
    }
    if (!getCompanyNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, companyName_);
    }
    if (!getPhotoUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, photoUrl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.notification.grpc.domain.Employer)) {
      return super.equals(obj);
    }
    com.wanpng.notification.grpc.domain.Employer other = (com.wanpng.notification.grpc.domain.Employer) obj;

    if (!getEmployerId()
        .equals(other.getEmployerId())) return false;
    if (!getCompanyName()
        .equals(other.getCompanyName())) return false;
    if (!getPhotoUrl()
        .equals(other.getPhotoUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMPLOYER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEmployerId().hashCode();
    hash = (37 * hash) + COMPANY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyName().hashCode();
    hash = (37 * hash) + PHOTO_URL_FIELD_NUMBER;
    hash = (53 * hash) + getPhotoUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.notification.grpc.domain.Employer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.notification.grpc.domain.Employer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.notification.grpc.domain.Employer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.Employer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.Employer)
      com.wanpng.notification.grpc.domain.EmployerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.notification.grpc.domain.EmployerProtos.internal_static_protos_domain_Employer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.notification.grpc.domain.EmployerProtos.internal_static_protos_domain_Employer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.notification.grpc.domain.Employer.class, com.wanpng.notification.grpc.domain.Employer.Builder.class);
    }

    // Construct using com.wanpng.notification.grpc.domain.Employer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      employerId_ = "";

      companyName_ = "";

      photoUrl_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.notification.grpc.domain.EmployerProtos.internal_static_protos_domain_Employer_descriptor;
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.domain.Employer getDefaultInstanceForType() {
      return com.wanpng.notification.grpc.domain.Employer.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.domain.Employer build() {
      com.wanpng.notification.grpc.domain.Employer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.notification.grpc.domain.Employer buildPartial() {
      com.wanpng.notification.grpc.domain.Employer result = new com.wanpng.notification.grpc.domain.Employer(this);
      result.employerId_ = employerId_;
      result.companyName_ = companyName_;
      result.photoUrl_ = photoUrl_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.notification.grpc.domain.Employer) {
        return mergeFrom((com.wanpng.notification.grpc.domain.Employer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.notification.grpc.domain.Employer other) {
      if (other == com.wanpng.notification.grpc.domain.Employer.getDefaultInstance()) return this;
      if (!other.getEmployerId().isEmpty()) {
        employerId_ = other.employerId_;
        onChanged();
      }
      if (!other.getCompanyName().isEmpty()) {
        companyName_ = other.companyName_;
        onChanged();
      }
      if (!other.getPhotoUrl().isEmpty()) {
        photoUrl_ = other.photoUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.notification.grpc.domain.Employer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.notification.grpc.domain.Employer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object employerId_ = "";
    /**
     * <code>string employer_id = 1;</code>
     * @return The employerId.
     */
    public java.lang.String getEmployerId() {
      java.lang.Object ref = employerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employer_id = 1;</code>
     * @return The bytes for employerId.
     */
    public com.google.protobuf.ByteString
        getEmployerIdBytes() {
      java.lang.Object ref = employerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employer_id = 1;</code>
     * @param value The employerId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployerId() {
      
      employerId_ = getDefaultInstance().getEmployerId();
      onChanged();
      return this;
    }
    /**
     * <code>string employer_id = 1;</code>
     * @param value The bytes for employerId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyName_ = "";
    /**
     * <code>string company_name = 2;</code>
     * @return The companyName.
     */
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company_name = 2;</code>
     * @return The bytes for companyName.
     */
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company_name = 2;</code>
     * @param value The companyName to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyName() {
      
      companyName_ = getDefaultInstance().getCompanyName();
      onChanged();
      return this;
    }
    /**
     * <code>string company_name = 2;</code>
     * @param value The bytes for companyName to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object photoUrl_ = "";
    /**
     * <code>string photo_url = 3;</code>
     * @return The photoUrl.
     */
    public java.lang.String getPhotoUrl() {
      java.lang.Object ref = photoUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        photoUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string photo_url = 3;</code>
     * @return The bytes for photoUrl.
     */
    public com.google.protobuf.ByteString
        getPhotoUrlBytes() {
      java.lang.Object ref = photoUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        photoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string photo_url = 3;</code>
     * @param value The photoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPhotoUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      photoUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string photo_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhotoUrl() {
      
      photoUrl_ = getDefaultInstance().getPhotoUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string photo_url = 3;</code>
     * @param value The bytes for photoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPhotoUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      photoUrl_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.Employer)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.Employer)
  private static final com.wanpng.notification.grpc.domain.Employer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.notification.grpc.domain.Employer();
  }

  public static com.wanpng.notification.grpc.domain.Employer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Employer>
      PARSER = new com.google.protobuf.AbstractParser<Employer>() {
    @java.lang.Override
    public Employer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Employer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Employer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Employer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.notification.grpc.domain.Employer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

