// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employer.grpc.proto

package com.wanpng.notification.grpc.domain;

public interface EmployerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.Employer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employer_id = 1;</code>
   * @return The employerId.
   */
  java.lang.String getEmployerId();
  /**
   * <code>string employer_id = 1;</code>
   * @return The bytes for employerId.
   */
  com.google.protobuf.ByteString
      getEmployerIdBytes();

  /**
   * <code>string company_name = 2;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 2;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string photo_url = 3;</code>
   * @return The photoUrl.
   */
  java.lang.String getPhotoUrl();
  /**
   * <code>string photo_url = 3;</code>
   * @return The bytes for photoUrl.
   */
  com.google.protobuf.ByteString
      getPhotoUrlBytes();
}
