// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employer.grpc.proto

package com.wanpng.notification.grpc.domain;

public final class EmployerProtos {
  private EmployerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_Employer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_Employer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!protos/domain/employer.grpc.proto\022\rpro" +
      "tos.domain\"H\n\010Employer\022\023\n\013employer_id\030\001 " +
      "\001(\t\022\024\n\014company_name\030\002 \001(\t\022\021\n\tphoto_url\030\003" +
      " \001(\tBh\n#com.wanpng.notification.grpc.dom" +
      "ainB\016EmployerProtosP\001Z/github.com/wanpng" +
      "/notification-grpc/grpc/domainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_domain_Employer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_Employer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_Employer_descriptor,
        new java.lang.String[] { "EmployerId", "CompanyName", "PhotoUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
