// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/invitation_request.grpc.proto

package com.wanpng.notification.grpc.domain;

public final class InvitationRequestProtos {
  private InvitationRequestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_InvitationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_InvitationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+protos/domain/invitation_request.grpc." +
      "proto\022\rprotos.domain\032\037google/protobuf/ti" +
      "mestamp.proto\"\331\001\n\021InvitationRequest\022\024\n\014j" +
      "obseeker_id\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\021\n\tis_vi" +
      "ewed\030\003 \001(\010\022\017\n\007is_seen\030\004 \001(\010\0220\n\014updated_w" +
      "hen\030\005 \001(\0132\032.google.protobuf.Timestamp\022\023\n" +
      "\013employer_id\030\006 \001(\t\022\016\n\006job_id\030\007 \001(\t\022\025\n\rin" +
      "vitation_id\030\010 \001(\005\022\016\n\006status\030\t \001(\tBq\n#com" +
      ".wanpng.notification.grpc.domainB\027Invita" +
      "tionRequestProtosP\001Z/github.com/wanpng/n" +
      "otification-grpc/grpc/domainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_protos_domain_InvitationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_InvitationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_InvitationRequest_descriptor,
        new java.lang.String[] { "JobseekerId", "Type", "IsViewed", "IsSeen", "UpdatedWhen", "EmployerId", "JobId", "InvitationId", "Status", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
