// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/invitation_response.grpc.proto

package com.wanpng.notification.grpc.domain;

public final class InvitationResponseProtos {
  private InvitationResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_InvitationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_InvitationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,protos/domain/invitation_response.grpc" +
      ".proto\022\rprotos.domain\032\037google/protobuf/t" +
      "imestamp.proto\"\353\001\n\022InvitationResponse\022\017\n" +
      "\007user_id\030\001 \001(\t\022\023\n\013employer_id\030\002 \001(\t\022\014\n\004t" +
      "ype\030\003 \001(\t\022\021\n\tis_viewed\030\004 \001(\010\022\017\n\007is_seen\030" +
      "\005 \001(\010\0220\n\014updated_when\030\006 \001(\0132\032.google.pro" +
      "tobuf.Timestamp\022\016\n\006job_id\030\007 \001(\t\022\024\n\014jobse" +
      "eker_id\030\010 \001(\t\022\025\n\rinvitation_id\030\t \001(\005\022\016\n\006" +
      "status\030\n \001(\tBr\n#com.wanpng.notification." +
      "grpc.domainB\030InvitationResponseProtosP\001Z" +
      "/github.com/wanpng/notification-grpc/grp" +
      "c/domainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_protos_domain_InvitationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_InvitationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_InvitationResponse_descriptor,
        new java.lang.String[] { "UserId", "EmployerId", "Type", "IsViewed", "IsSeen", "UpdatedWhen", "JobId", "JobseekerId", "InvitationId", "Status", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
