// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/jobseeker.grpc.proto

package com.wanpng.notification.grpc.domain;

public interface JobseekerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.Jobseeker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jobseeker_id = 1;</code>
   * @return The jobseekerId.
   */
  java.lang.String getJobseekerId();
  /**
   * <code>string jobseeker_id = 1;</code>
   * @return The bytes for jobseekerId.
   */
  com.google.protobuf.ByteString
      getJobseekerIdBytes();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string photo_url = 4;</code>
   * @return The photoUrl.
   */
  java.lang.String getPhotoUrl();
  /**
   * <code>string photo_url = 4;</code>
   * @return The bytes for photoUrl.
   */
  com.google.protobuf.ByteString
      getPhotoUrlBytes();
}
