// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/jobseeker.grpc.proto

package com.wanpng.notification.grpc.domain;

public final class JobseekerProtos {
  private JobseekerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_Jobseeker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_Jobseeker_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"protos/domain/jobseeker.grpc.proto\022\rpr" +
      "otos.domain\"[\n\tJobseeker\022\024\n\014jobseeker_id" +
      "\030\001 \001(\t\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast_name\030" +
      "\003 \001(\t\022\021\n\tphoto_url\030\004 \001(\tBi\n#com.wanpng.n" +
      "otification.grpc.domainB\017JobseekerProtos" +
      "P\001Z/github.com/wanpng/notification-grpc/" +
      "grpc/domainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_domain_Jobseeker_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_Jobseeker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_Jobseeker_descriptor,
        new java.lang.String[] { "JobseekerId", "FirstName", "LastName", "PhotoUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
